import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Homepage from '../components/homepage/homepage'
import MenuList from '../components/menu_list/menu_list'
import styles from '../styles/Home.module.css'
import { menuListItem  } from '../utils/menuData';

const menuList = [
  {id: 1, title: 'home' }, 
  {id: 2, title: 'skills' }, 
  {id: 3, title: 'experience' }, 
  {id: 4, title: 'education' }, 
]


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>이현주의 미니홈피</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/content.ico" />
      </Head>

      <main className={styles.main}>
        <Homepage />
      {/* <MenuList menuList={menuList}/> */}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.linkedin.com/in/hyunjoo-l-0a53011a3"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/linkedin.png" alt="Linkedin Logo" width={33} height={30} />
          </span>
        </a>
        <a
          href="https://github.com/madisonrubylee"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/github.png" alt="Github Logo" width={33} height={30} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
